### ISSUE TITLE
Can this library be used in react-native applications

### ISSUE THREAD

**Issue by patrickCode** [googlemaps/react-wrapper#537]
Can this library be used in a React-Native (Android and iOS) application ?

**Comment by nora-soderlund** [comment]
It can not, since it depends on the [@googlemaps/js-api-loader](https://github.com/googlemaps/js-api-loader) library which injects a `<script>` tag to the `document`; thus using DOM elements which does not exist in React Native, see: https://github.com/googlemaps/js-api-loader/blob/main/src/index.ts#L464

Instead, there's a 3rd party wrapper for React Native which uses the iOS and Android SDK (and the JavaScript API for web platforms!): https://github.com/react-native-maps/react-native-maps
