### ISSUE TITLE
Custom Marker position is false on zoom out.

### ISSUE THREAD

**Issue by tmmschmit** [googlemaps/react-wrapper#568]
#### Environment details

I tried with: https://stackblitz.com/edit/github-xckc5p?file=package.json
And on my local env:
- Linux
- React ^18.0
- @googlemaps/react-wrapper ^1.1
- 
#### Steps to reproduce

  1. Follow the example in the documentation https://developers.google.com/maps/documentation/javascript/markers#symbols

#### Code example

 On the official example it's not obvious, but by setting the coordinates close to a river it's more obvious: https://stackblitz.com/edit/github-xckc5p?file=index.ts

With custom marker:
![Peek 2022-10-24 08-08](https://user-images.githubusercontent.com/60105862/197522964-220bef2c-f03b-4904-8620-0378edebedad.gif)

Without:
![Peek 2022-10-24 08-09](https://user-images.githubusercontent.com/60105862/197523208-132d9f06-8704-498a-b92a-44102f422970.gif)

Thanks!

**Comment by porkytheblack** [comment]
any luck with this? Having a similar issue.

**Comment by nora-soderlund** [comment]
This happens because the provided SVG path in the example is not centered and not properly sized, which causes the proportions to mess up at a larger scale.

You can test a proper example with a square path:
```js
const svgMarker = {
    path: "M 10 10 H 30 V 30 H 10 L 10 10",
    fillColor: "blue",
    fillOpacity: 0.6,
    strokeWeight: 0,
    rotation: 0,
    scale: 2,
    anchor: new google.maps.Point(15, 30),
};
```

But if you want to use the SVG provided in the example, I've updated the base points so that the path is centered on it's X axis and the Y axis is more defined:
`M-1.547 12l6.563-6.609-1.406-1.406-5.156 5.203-2.063-2.109-1.406 1.406zM0 0q2.906 0 4.945 2.039t2.039 4.945q0 1.453-0.727 3.328t-1.758 3.516-2.039 3.070-1.711 2.273l-0.75 0.797q-0.281-0.328-0.75-0.867t-1.688-2.156-2.133-3.141-1.664-3.445-0.75-3.375q0-2.906 2.039-4.945t4.945-2.039z` and it can be used with an anchor of 0x20, because 0 is the center of the path now and 20 is the bottom of the path:

```js
  const svgMarker = {
    path: "M-1.547 12l6.563-6.609-1.406-1.406-5.156 5.203-2.063-2.109-1.406 1.406zM0 0q2.906 0 4.945 2.039t2.039 4.945q0 1.453-0.727 3.328t-1.758 3.516-2.039 3.070-1.711 2.273l-0.75 0.797q-0.281-0.328-0.75-0.867t-1.688-2.156-2.133-3.141-1.664-3.445-0.75-3.375q0-2.906 2.039-4.945t4.945-2.039z",
    fillColor: "blue",
    fillOpacity: 0.6,
    strokeWeight: 0,
    rotation: 0,
    scale: 2,
    anchor: new google.maps.Point(0, 20),
  };
```

If you have an issue with your own SVG path, please provide it together with your anchor setting. See https://jsfiddle.net/ymhstku9/ for an example using this code: https://developers.google.com/maps/documentation/javascript/examples/marker-symbol-custom
