### ISSUE TITLE
ReferenceError: google is not defined

### ISSUE THREAD

**Issue by shane806** [googlemaps/react-wrapper#743]
I'm getting a ref. error if I define a class that extends google.maps.OverlayView, but works as expected if that code is commented out.

[this repo](https://github.com/shane806/mini-maps-issue) is a MRE I created which demonstrates the issue. It's essentially a nextjs clone of the react code in googlemaps/samples

#### Environment details

1. using nextjs with react-wrapper
2. macOS 14
3. react-wrapper v1.1.35

#### Steps to reproduce

1. clone repo
2. run dev server
3. MapsComponents.tsx is where the overlay class is defined as well as the map component. The Wrapper component is defined in GoogleMapContext.tsx

#### Stack trace

<img width="959" alt="stacktrace 1" src="https://github.com/googlemaps/react-wrapper/assets/47383634/6eee09d0-f13d-4f86-a87e-0ee725b707e9">
<img width="959" alt="stacktrace 2" src="https://github.com/googlemaps/react-wrapper/assets/47383634/32f31604-6825-4957-9acc-f08ca28df88b">
<img width="959" alt="stacktrace 3" src="https://github.com/googlemaps/react-wrapper/assets/47383634/dfc73598-72d5-458e-8dc8-50fdc60466a5">
<img width="959" alt="stacktrace 4" src="https://github.com/googlemaps/react-wrapper/assets/47383634/8487d0bc-9418-4d0c-9d43-91e47c4fe25d">

**Comment by usefulthink** [comment]
Hi @shane806,

this is a very common problem with the google maps API.
Since the API loads in a separate request, it's exported symbols (`google.maps.OverlayView` in your case) are not available in the JS runtime at the time your class is loaded and the `extends google.maps.OverlayView` is evaluated. 

There are two ways you could deal with this:
 - wait with loading your custom overlay until google maps is loaded (for example using `const {CustomOverlay} = await import('...')`, which should also work with most bundlers these days)
 - don't use `extends` for your custom overlay (this is what we've done a lot).

In the latter case, a skeleton implementation could look something like this:

```javascript
class CustomOverlay {
  constructor() {
    this.overlay = new google.maps.OverlayView();
    this.overlay.onAdd = () => this.onAdd();
    this.overlay.onRemove = () => this.onRemove();
    this.overlay.draw = () => this.draw();
  }
  onAdd() { /* ... */ }
  onRemove() { /* ... */ }
  draw() {
    const p = this.overlay.getProjection();
    const pane = this.overlay.getPanes().floatPane;

    // [...]
  }

  setMap(map) { this.overlay.setMap(map); }
  getMap() { return this.overlay.getMap(); }
}


// ... somewhere else (when api is loaded):
const map = new google.maps.Map( /* ... */ );
const overlay = new CustomOverlay();
overlay.setMap(map);
```

@wangela it would be great if this detail (can't declare a subclass until after the maps api is loaded) was somehow mentioned in the documentation at https://developers.google.com/maps/documentation/javascript/customoverlays#subclass

**Comment by shane806** [comment]
Thanks @usefulthink, that second option will integrate with my current custom overlay implementation just fine.

I figured it was most likely some issue with the maps API not being loaded/available, but this interface extension:

```
interface MapProps extends google.maps.MapOptions {
	style: { [key: string]: string };
	onClick?: (e: google.maps.MapMouseEvent) => void;
	onIdle?: (map: google.maps.Map) => void;
	children?: ReactNode;
}
```
which is similarly defined in the file's global scope doesn't cause a reference error to be thrown. Is it because `google.maps.OverlayView` is a class or something?

**Comment by usefulthink** [comment]
Oh, this is different since it's just a typescript interface, and those don't actually exist in the JS runtime. The type-definitions for the Google Maps API are available in the `@types/google.maps` package from npm, but those are basically just to let your editor know what properties are available on which objects.

**Comment by shane806** [comment]
Oh right. makes total sense now that I'm thinking about it. 

Thanks again!
